version: "3"
services:
  app:
    image: pic-share:production
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_VERSION: 18
        PHP: 8.2
    env_file: .env.production
    volumes:
      - ./storage:/app/storage
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
  mysql:
    image: "mysql/mysql-server:8.0"
    env_file: .env.production
    volumes:
      - "prod.mysql:/var/lib/mysql"
    networks:
      - app
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      retries: 10
      timeout: 5s
    restart: always
  redis:
    image: redis:7-alpine
    volumes:
      - "prod.redis:/data"
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always
volumes:
  prod.redis:
    driver: local
  prod.mysql:
    driver: local
networks:
  app:
    driver: bridge
