# For more information: https://laravel.com/docs/sail
version: "3"
services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
                # POSTGRES_VERSION: 15
                NODE_VERSION: 18
        image: sail-8.2/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        # ports:
        #     - "${APP_PORT:-80}:80"
        #     - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mysql
            # - pgsql
            - redis
            - selenium
    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    # pgsql:
    #     image: postgres:15
    #     ports:
    #         - "${FORWARD_DB_PORT:-5432}:5432"
    #     environment:
    #         PGPASSWORD: "${DB_PASSWORD:-secret}"
    #         POSTGRES_DB: "${DB_DATABASE}"
    #         POSTGRES_USER: "${DB_USERNAME}"
    #         POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    #     volumes:
    #         - "sailpostgresql:/var/lib/postgresql/data"
    #         - "./vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             [
    #                 "CMD",
    #                 "pg_isready",
    #                 "-q",
    #                 "-d",
    #                 "${DB_DATABASE}",
    #                 "-U",
    #                 "${DB_USERNAME}",
    #             ]
    redis:
        image: "redis:7-alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sailredis:/data"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
    selenium:
        image: "selenium/standalone-chrome"
        # ports:
        #     - "${FORWARD_SELENIUM_PORT:-4444}:4444"
        #     - "${FORWARD_SELENIUM_HEADFUL_PORT:-7900}:7900"
        volumes:
            - "/dev/shm:/dev/shm"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    # sailpostgresql:
    #     driver: local
    sailredis:
        driver: local
    sail-mysql:
        driver: local
