[supervisord]
user=root
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
priority=1

[program:crond]
command=crond -f
autostart=true
autorestart=true
priority=2

[program:horizon]
command=php /var/www/artisan horizon
directory=/var/www
autostart=true
autorestart=true
user=www-data
priority=3
stdout_logfile=/var/www/storage/logs/horizon.log
stderr_logfile=/var/www/storage/logs/horizon-error.log

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=4
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log

