name: Main

on:
  push:
    branches: [1.x]
  pull_request:
    branches: [1.x]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Log in to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build Docker image
      #   run: docker build -t ghcr.io/${{ github.repository_owner }}/pic-share:prod_${{ env.COMMIT_HASH }} -f Dockerfile.prod .

      # - name: Push Docker image
      #   run: docker push ghcr.io/${{ github.repository_owner }}/pic-share:prod_${{ env.COMMIT_HASH }}

      - name: Inject .env from secret
        run: |
          echo "${{ secrets.ENV_TESTING }}" > .env

      - name: Install Sail
        run: |
          docker run --rm \
          -u "$(id -u):$(id -g)" \
          -v "$(pwd):/var/www/html" \
          -w /var/www/html \
          laravelsail/php82-composer:latest \
          composer install --ignore-platform-reqs

      - name: Start Sail
        run: vendor/bin/sail up -d

      - name: Wait for Laravel service to be ready (with debugging)
        run: |
          echo "Checking running containers:"
          docker compose ps

          echo "Starting wait loop for laravel.test service..."
          until docker compose exec -T laravel.test php -r "echo 'Service is up';" > /dev/null 2>&1; do
            echo "[$(date)] Waiting for Laravel service to start..."

            echo "--- Container logs (last 10 lines) ---"
            docker compose logs --tail=10 laravel.test || echo "No logs yet."

            echo "--- Container status ---"
            docker compose ps laravel.test || echo "Container not found."

            sleep 5
          done

          echo "Laravel service is ready!"

      - name: Tests
        run: vendor/bin/sail test

      - name: E2E Tests
        run: vendor/bin/sail dusk

      # - name: Upload Screenshots
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: screenshots
      #     path: tests/Browser/screenshots

      # - name: Upload Console Logs
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: console
      #     path: tests/Browser/console

      - name: Shut down containers
        if: always()
        run: vendor/bin/sail down

      - name: Cleanup registry
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.repository_owner }}/pic-share
          package-type: container
          min-versions-to-keep: 5
