name: Build and Test Docker Images
on:
  push:
    branches: [main, 1.x]
  pull_request:
    branches: [main, 1.x]
env:
  COMMIT_HASH: ${{ github.sha }}
  APP_TEST_IMAGE: ghcr.io/${{ github.repository_owner }}/pic-share-app-test:${{ github.sha }}
  APP_PROD_IMAGE: ghcr.io/${{ github.repository_owner }}/pic-share-app-prod:${{ github.sha }}
  APP_PROD_IMAGE_LATEST: ghcr.io/${{ github.repository_owner }}/pic-share-app-prod:latest

jobs:
  build:
    runs-on: ubuntu-latest
    name: Verify Docker Image Builds and Push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app prod image
        run: |
          docker build -t $APP_PROD_IMAGE -f  docker/production/Dockerfile .
          docker push $APP_PROD_IMAGE

      - name: Build and push app test image
        run: |
          docker build -t $APP_TEST_IMAGE -f docker/test/Dockerfile .
          docker push $APP_TEST_IMAGE

  test:
    runs-on: ubuntu-latest
    needs: build
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull test images
        run: |
          docker pull $APP_TEST_IMAGE

      - name: Inject .env from secret
        run: echo "${{ secrets.ENV_TESTING }}" > .env

      - name: Start docker containers
        run: docker compose -f docker-compose.test.yaml up -d

      - name: Tests
        run: docker compose exec -T nginx php artisan test

      - name: Wait for nginx to be healthy
        run: |
          for i in {1..10}; do
            if docker inspect --format='{{json .State.Health.Status}}' $(docker compose ps -q nginx) | grep -q "healthy"; then
              echo "nginx is healthy"
              break
            fi
            echo "Waiting for nginx to become healthy..."
            sleep 3
          done

      - name: Check nginx is up
        run: docker compose exec -T selenium curl -v nginx

      - name: E2E Tests
        run: docker compose exec -T nginx php artisan dusk

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: console
          path: tests/Browser/console

      - name: Shut down containers
        if: always()
        run: docker compose -f docker-compose.test.yaml down

  post-build:
    runs-on: ubuntu-latest
    needs: test
    name: Push Final Production Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull app production test image
        run: |
          docker pull $APP_PROD_IMAGE

      - name: Tag image with commit hash
        run: |
          docker tag $APP_PROD_IMAGE ${{ env.APP_PROD_IMAGE_LATEST }}
      - name: Push new tag
        run: |
          docker push ${{ env.APP_PROD_IMAGE_LATEST }}

      - name: Cleanup app registry
        uses: actions/delete-package-versions@v5
        with:
          package-name: pic-share-app-prod
          package-type: container
          min-versions-to-keep: 5

      - name: Cleanup nginx registry
        uses: actions/delete-package-versions@v5
        with:
          package-name: pic-share-app-test
          package-type: container
          min-versions-to-keep: 5
