on:
  push:
    branches: [main, 1.x]
  pull_request:
    branches: [main, 1.x]
env:
  APP_TEST_IMAGE: ghcr.io/${{ github.repository_owner }}/pic-share-app:test
  NGINX_PROD_IMAGE: ghcr.io/${{ github.repository_owner }}/pic-share-nginx:prod
  APP_PROD_IMAGE: ghcr.io/${{ github.repository_owner }}/pic-share-app:prod

jobs:
  build:
    runs-on: ubuntu-latest
    name: Verify Docker Image Builds and Push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app prod image
        run: |
          docker build -t $APP_PROD_IMAGE -f  docker/production/app/Dockerfile.prod .
          docker push $APP_PROD_IMAGE

      - name: Build and push app test image
        run: |
          docker build -t $APP_TEST_IMAGE -f docker/production/app/Dockerfile.test .
          docker push $APP_TEST_IMAGE

      - name: Build and push nginx prod image
        run: |
          docker build -t $NGINX_PROD_IMAGE -f docker/production/nginx/Dockerfile .
          docker push $NGINX_PROD_IMAGE

  test:
    runs-on: ubuntu-latest
    needs: build
    name: Run Tests with Pulled Test Images

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull test images
        run: |
          docker pull $APP_TEST_IMAGE
          docker pull $NGINX_PROD_IMAGE

      - name: Inject .env from secret
        run: echo "${{ secrets.ENV_TESTING }}" > .env

      - name: Start docker containers
        run: docker compose -f docker-compose.test.yaml up -d

      - name: Tests
        run: docker compose exec -T app php artisan test

      - name: E2E Tests
        run: docker compose exec -T app php artisan dusk

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: console
          path: tests/Browser/console

      - name: Shut down containers
        if: always()
        run: docker compose -f docker-compose.test.yaml down

  post-build:
    runs-on: ubuntu-latest
    needs: test
    name: Push Final Production Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull app production test image
        run: |
          docker pull $APP_PROD_IMAGE

      - name: Tag image with commit hash
        run: |
          docker tag $APP_PROD_IMAGE ghcr.io/${{ github.repository_owner }}/pic-share:prod-${{ env.COMMIT_HASH }}

      - name: Push new tag
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/pic-share:prod-${{ env.COMMIT_HASH }}

      - name: Pull nginx production test image
        run: |
          docker pull $NGINX_PROD_IMAGE

      - name: Tag image with commit hash
        run: |
          docker tag $NGINX_PROD_IMAGE ghcr.io/${{ github.repository_owner }}/pic-share:nginx-${{ env.COMMIT_HASH }}

      - name: Push new tag
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/pic-share:nginx-${{ env.COMMIT_HASH }}

      - name: Cleanup app registry
        uses: actions/delete-package-versions@v5
        with:
          package-name: pic-share-app
          package-type: container
          min-versions-to-keep: 5

      - name: Cleanup nginx registry
        uses: actions/delete-package-versions@v5
        with:
          package-name: pic-share-nginx
          package-type: container
          min-versions-to-keep: 5
