name: Main

on:
  push:
    branches: [1.x]
  pull_request:
    branches: [1.x]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env files
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env \
          && echo "${{ secrets.ENV_DUSK }}" > .env.dusk.local

      - name: Set up
        run: |
          docker run --rm \
          -u "$(id -u):$(id -g)" \
          -v "$(pwd):/var/www/html" \
          -w /var/www/html \
          laravelsail/php82-composer:latest \
          composer install --ignore-platform-reqs

      - name: Build
        run: |
          ./vendor/bin/sail build --no-cache

      # - name: Run
      #   run: |
      #     ./vendor/bin/sail up -d \
      #     && echo "Waiting for App to launch on port 80..."

      #     while ! curl --output /dev/null --silent --head --fail http://0.0.0.0:80; do
      #       sleep 1 && echo "Waiting for app to start...";
      #     done;

      #     echo "App launched"
      #     exit;

      - name: Run
        run: |
          ./vendor/bin/sail up -d \
          && exit;

      - name: Wait for app to start
        run: |
          echo "Waiting for App to start on port 80..."

          sleep 60
          # while ! curl --output /dev/null --silent --head --fail http://0.0.0.0:80; do
          #   sleep 10 && docker container ls --all;
          # done;

          echo "App started"
          exit;

      - name: Install front end
        run: |
          ./vendor/bin/sail npm install
          && exit;

      - name: Build front end
        run: |
          ./vendor/bin/sail npm run build \
          && exit;

      - name: Feature test
        run: |
          ./vendor/bin/sail test --coverage

      - name: E2E test
        run: |
          ./vendor/bin/sail dusk
