name: Main

on:
  push:
    branches: [1.x]
  pull_request:
    branches: [1.x]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Create env files"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env \
          && echo "${{ secrets.ENV_DUSK }}" > .env.dusk.local

      - name: Set up
        run: |
          docker run --rm \
          -u "$(id -u):$(id -g)" \
          -v "$(pwd):/var/www/html" \
          -w /var/www/html \
          laravelsail/php82-composer:latest \
          composer install --ignore-platform-reqs

      - name: Run
        run: |
          ./vendor/bin/sail up \
          & echo "Waiting for App to launch on 80..."

          while ! curl --output /dev/null --silent --head --fail http://localhost:80; do 
            sleep 1 && echo -n .;
          done;

          echo "App launched"
          exit;

      - name: Set up scheduler
        run: |
          ./vendor/bin/sail php artisan schedule:work

      - name: Set up Horizon
        run: |
          ./vendor/bin/sail php artisan horizon

      - name: Set up front end
        run: |
          ./vendor/bin/sail npm run dev

      - name: Feature test
        run: |
          ./vendor/bin/sail test --coverage

      - name: E2E test
        run: |
          ./vendor/bin/sail dusk
